language: objective-c
script:
  - xctool -project TestSourceTree.xcodeproj -scheme TestSourceTree -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project TestSourceTree.xcodeproj -scheme TestSourceTreeTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
